### PR TITLE
Full french translation

### PR DESCRIPTION
**Pull request by Kirvx**
:+1:

I'll be back to correct some strings if they are incorrect or if you update the file, or if a string is too long, if you're OK.

### CODE REVIEW

**Comment by rubensayshi** [comment]
@OACDesigns ! now you don't have to anymore xD

@Kirvx thanks a lot! we were planning of seperating the translations this week into their own repo and making a small tool to generate a CSV out of it to make it easier to translate them, respect for doing it the JSON way ;-)

**Comment by OACDesigns** [comment]
@Kirvx wow, brilliant job! I think you've managed to save all French speakers from my terrible grammar and spelling ;) 

I'll merge and test today, and will report back here.
Thanks again.

**Comment by Kirvx** [comment]
Ok thanks guys :)

**Comment by rubensayshi** [comment]
merged as part of https://github.com/blocktrail/blocktrail-wallet/pull/15  
translations were moved to https://github.com/blocktrail/blocktrail-wallet-translations/blob/master/translations/french.json

**Pull request closed without merging**
